#!/bin/bash
set -euo pipefail

# Variables
export MAIA_PREFIX=$CONDA_PREFIX
export PYTHON_VERSION=3.9 # or 3.10 or 3.11, depending on what's available

# Clone le dépôt Maia
git https://github.com/onera/Maia.git

cd Maia

# Initialise et met à jour les sous-modules
git submodule update --init 

# Crée et entre dans le répertoire de construction
mkdir -p build
cd build

# Configure CMake
cmake -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX \
      -DMAIA_ENABLE_PYTHON=ON \
      -DPYTHON_EXECUTABLE=$(which python) \
      ..

# Compile et installe
make -j$(nproc) install

# Configure PYTHONPATH
echo "export PYTHONPATH=$CONDA_PREFIX/lib:$PYTHONPATH" >> /home/jovyan/.bashrc

